### ISSUE TITLE
Tool proposal for managing community translations

### ISSUE THREAD

**Issue by ilyaspiridonov** [w3c/translation-management#16]
Hi,
Please consider using [GitLocalize](https://gitlocalize.com) for managing community translations.
It's free, has two-way GitHub sync and supports .md

**Comment by dontcallmedom** [comment]
Hi @ilyaspiridonov,

I had considered this when working on the system a couple of years ago, and I think we interacted back then; I think the problem was that gitlocalize doesn't handle HTML documents, which is the key format we would need in our case.

**Comment by ilyaspiridonov** [comment]
Hi @dontcallmedom 
Thanks, indeed, we're focused on Markdown and key-value files at the moment (.json, .po, .yaml etc), but HTML is something we have on our roadmap. Let's talk later once we add proper support for HTML. 
Cheers,
-I
